### PR TITLE
+ String#match?, Regexp#match?

### PR DESCRIPTION
**Pull request by yjukaku**
- Adds String.match? that returns a bool (https://github.com/ruby/spec/blob/master/core/string/match_spec.rb#L153)
- Adds Regexp.match? that returns a bool (https://github.com/ruby/spec/blob/master/core/regexp/match_spec.rb#L115)

I would assume it's not possible to replicate the 'returns true but does not set Regexp.last_match' part of the new match? methods, but I would think that's acceptable.

I'm a little confused on how to write specs for this (or if they are needed), but please let me know!

### CODE REVIEW

**Comment by marcandre** [comment]
Thanks for the PR.

I'm quite hesitant here. Not updating `$~`, `$1`, etc..., can be very important. I'm not sure this is an acceptable backport.

**Comment by marcandre** [comment]
Actually, this could be implemented correctly (i.e. without side effects) using a `Fiber`.

PS: tests don't pass currently, sorry. You can test manually with `rake test[string/match]`

**Comment by yjukaku** [comment]
Ah, I see. So something like the following would break?
```ruby
r = /abc/
r =~ "abc"
r.match?("ab")
# $~ should be "abc", but would be nil
```

**Comment by marcandre** [comment]
Merged.
Had to fix a couple of things, in particular some errors that the `ruby/spec` highlighted.
Thanks for the PR

**Comment by marcandre** [comment]
PS: Released in 3.8.0

**Comment by yjukaku** [comment]
Thanks!

I had noticed there were some bugs yesterday or the day before but didn't get around to submitting an update. Sorry about that!

**Pull request closed without merging**
